#!/usr/bin/env Rscript
# 铁律：运行记录(query_logs)只是参考，不能跳过 rail_review/debate_analysis 审查
# scRNA-seq聚类分析 — Proven Analysis Script
# Auto-generated by MemOmics Skill Migration
#
# USAGE: This script is loaded by MemOmics agent when the skill is triggered.
# Parameters are adapted based on species, tissue, and condition.

# Step 1: Normalize (SCTransform)
# Step 2: HVG selection
# Step 3: PCA + PC selection
# Step 4: Batch correction (Harmony)
# Step 5: Cluster (Leiden)
# Step 6: UMAP visualization
# Step 7: Cell annotation

# ── Parameters (adapt before running) ────────────────────────────────
# TODO: Fill in parameters based on data quality and literature

# ── Main Pipeline ─────────────────────────────────────────────────────
# TODO: Proven code will be saved here after successful execution + review

# ── Save Results ──────────────────────────────────────────────────────
# TODO: Export figures, results, and metadata
