# 铁律：运行记录(query_logs)只是参考，不能跳过 rail_review/debate_analysis 审查
# ============================================================
# 🔒 MemOmics 审查铁律 — 执行本脚本前后的强制步骤
# ============================================================
# 执行前必须: rail_review(action="pre")  — 环境检查 + 参数校验 + 代码审查
# 执行后必须: rail_review(action="post") — 结果质量评估 + 图表检查 + 数值检查
# 参数有争议: debate_analysis(topic=..., context=...) — 多角色辩论
# 执行失败:   skill_evolution(action="record_error") — 记录错误
# 修复成功:   skill_evolution(action="update_script") — 替换脚本
# ============================================================
#!/usr/bin/env python3
""" Analyze Hemodynamic Data — Proven Analysis Script
Auto-generated by MemOmics Skill Migration

USAGE: This script is loaded by MemOmics agent when the skill is triggered.
Parameters are adapted based on species, tissue, and condition.
"""



# ── Parameters (adapt before running) ────────────────────────────────
# TODO: Fill in parameters based on data quality and literature

# ── Main Pipeline ─────────────────────────────────────────────────────
# TODO: Proven code will be saved here after successful execution + review

# ── Save Results ──────────────────────────────────────────────────────
# TODO: Export figures, results, and metadata
