#!/usr/bin/env Rscript
# 铁律：运行记录(query_logs)只是参考，不能跳过 rail_review/debate_analysis 审查
# scRNA-seq质量控制 — Proven Analysis Script
# Auto-generated by MemOmics Skill Migration
#
# USAGE: This script is loaded by MemOmics agent when the skill is triggered.
# Parameters are adapted based on species, tissue, and condition.

# Step 1: Read10X/ReadH5
# Step 2: QC metrics (mt/ribo)
# Step 3: Doublet removal
# Step 4: Ambient RNA (SoupX)
# Step 5: Filter cells
# Step 6: QC report + Violin

# ── Parameters (adapt before running) ────────────────────────────────
# TODO: Fill in parameters based on data quality and literature

# ── Main Pipeline ─────────────────────────────────────────────────────
# TODO: Proven code will be saved here after successful execution + review

# ── Save Results ──────────────────────────────────────────────────────
# TODO: Export figures, results, and metadata
